Feat html file name
web-infra-dev/rspack pull request #2673
Opened 2023-04-08 14:22 UTC by suxin2017

## Summary

## Related issue (if exists)

https://github.com/web-infra-dev/rspack/issues/2638

## Types of changes

- [ ] Docs change / Dependency upgrade
- [x] Bug fix
- [ ] New feature / Improvement
- [ ] Refactoring
- [ ] Breaking change

## Checklist

- [ ] I have added changeset via `pnpm run changeset`.
- [x] I have added tests to cover my changes.

2023-04-08 14:30 UTC, ahabhgk approved these changes
Thanks!

2023-04-08 14:32 UTC, ahabhgk commented
`pnpm run changeset` is needed for fix

2023-04-09 00:26 UTC, suxin2017 commented
> `pnpm run changeset` is needed for fix

I'm not sure I did the right thing. Please check

2023-04-09 01:45 UTC, ahabhgk submitted a review, later dismissed

2023-04-09 04:17 UTC, ahabhgk requested changes

2023-04-09 04:17 UTC, ahabhgk commented on crates/rspack_plugin_html/src/plugin.rs
> +        }),
```suggestion
      name: Path::new(&url).file_stem().map(|s| s.to_string_lossy().to_string()),
```

2023-04-09 06:31 UTC, ahabhgk approved these changes

2023-04-09 06:32 UTC, merged