feat(user option):add ignoreWarnings option
web-infra-dev/rspack pull request #2987
Opened 2023-04-29 22:53 UTC by nagy-nabil

WIP #2979

- [x] add `ignoreWarnings` option in rspack options schema 
- [ ] create ignoreWarnings plugin (still don't know what compilation hook to use)
- [x] activate the plugin when the user enter `ignoreWarnings` option

2023-04-29 22:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/web-infra-dev/rspack?pullRequest=2987) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/web-infra-dev/rspack?pullRequest=2987) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/web-infra-dev/rspack?pullRequest=2987) it.</sub>

2023-05-03 14:29 UTC, ahabhgk approved these changes
LGTM, Thanks!

2023-05-03 14:33 UTC, ahabhgk requested changes

2023-05-03 14:55 UTC, nagy-nabil commented on .changeset/olive-lobsters-tie.md
> +"@rspack/core": minor
updated it, thank you

2023-05-04 08:31 UTC, nagy-nabil commented
@ahabhgk i updated the inline snapshot in defaults.unittest, am I missing anything else?

2023-05-04 10:44 UTC, ahabhgk approved these changes
LGTM, thanks!

2023-05-04 10:45 UTC, merged