chore: use self hosted ci
web-infra-dev/rspack pull request #4360
Opened 2023-10-18 12:05 UTC by jerrykingxyz

## Summary

fix build cache not work in CI and support use self hosted runner. Some CI data are as follows:

* github action - https://github.com/web-infra-dev/rspack/actions/runs/6558444654
* pr with self hosted - https://github.com/web-infra-dev/rspack/actions/runs/6559111173

| | github action | pr with self hosted |
|--|--|--|
| build rspack |  23m4s | 5m46s |
| build job |  27m56s | 9m42s |
| rust test | 6m37s | 3m13s |
| nodejs test | 7m12s | 5m43s |
| one time CI | 39m14s | 15m46s |

This new runner can be toggled by the CI action variables `LINUX_RUNNER_LABELS`. See https://github.com/web-infra-dev/rspack/settings/variables/actions (permission required).

## Test Plan

No

## Require Documentation?

- [x] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

2023-10-18 12:50 UTC, hardfist commented
does it support fallback to github runner when self-hosted is down？

2023-10-19 02:23 UTC, Boshen commented on .github/actions/docker-build/action.yml
> +          bash -c "$code"
Let's land this first in a PR prior this this PR, so the rest of this PR is revertible.

2023-10-19 02:24 UTC, Boshen requested changes

2023-10-19 02:24 UTC, Boshen commented on .github/actions/docker-build/action.yml
> +        "
Let's land this first in a PR prior this this PR, so the rest of this PR is revertible.

2023-10-19 02:49 UTC, Boshen approved these changes

2023-10-19 02:52 UTC, merged