feat: support WarnCaseSensitiveModulesPlugin
web-infra-dev/rspack pull request #4379
Opened 2023-10-21 08:33 UTC by OceanPresentChao

## Summary

issue: [4347](https://github.com/web-infra-dev/rspack/issues/4347)

This Plugin warns when there are case sensitive modules in the compilation

## Test Plan

run test in `webpack-test/errors/case-sensitive`

## Require Documentation?

- [x] No
- [ ] Yes, the corresponding rspack-website PR is \_\_

2023-10-22 12:24 UTC, ahabhgk commented
Snapshot needs update, you can run `pnpm run test -- -u` under `packages/rspack` to update them

2023-10-29 06:02 UTC, OceanPresentChao commented
> Snapshot needs update, you can run `pnpm run test -- -u` under `packages/rspack` to update them

Could you take a review? Thanks

2023-11-02 13:00 UTC, ahabhgk commented
Sorry for the delay, will take a look tomorrow

2023-11-06 05:21 UTC, ahabhgk requested changes
Generally looks great, it's a right solution, but still need to make some little changes

2023-11-06 05:21 UTC, ahabhgk commented on crates/rspack_plugin_warn_sensitive_module/src/lib.rs
> +  fn module_ids(&self, compilation: &mut Compilation) -> rspack_error::Result<()> {
Should use `seal` instead of `module_ids`

2023-11-06 05:21 UTC, ahabhgk commented on crates/rspack_plugin_warn_sensitive_module/src/lib.rs
> +    modules: &Vec<&&Box<dyn Module>>,
Should respect clippy and make the type simpler

2023-11-06 05:21 UTC, ahabhgk commented on crates/rspack_ids/src/lib.rs
> +pub mod id_helpers;
No need to change

2023-11-06 05:21 UTC, ahabhgk commented on packages/rspack/tests/hotCases/warnings/case-sensitive/index.js
> +it("should return different modules with different casing",  (done)=> {
This case seems unnecessary to be added in hotCases

2023-11-06 05:21 UTC, ahabhgk commented on webpack-test/cases/errors/case-sensitive/warnings.js
> +	[/There are multiple modules with names that only differ in casing/, /(case-sensitive.A\.js)|(case-sensitive.B.file\.js)/, /(case-sensitive.a\.js)|(case-sensitive.b.file\.js)/]
Don't change test under `webpack-test`, try your best to pass it or track it in a issue

2023-11-06 09:44 UTC, ahabhgk approved these changes
LGTM, thanks!

2023-11-06 11:58 UTC, ahabhgk approved these changes

2023-11-06 12:33 UTC, merged