docs(landingpage): totally NEW LandingPage
web-infra-dev/rspack pull request #7550
Opened 2024-08-13 06:57 UTC by SoonIter

## Summary

## Checklist

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).

2024-08-21 13:38 UTC, SoonIter commented
"extract the shared components"
I think rspress theme is a better choice

2024-08-22 02:51 UTC, chenjiahan commented on website/theme/components/Landingpage/Benchmark/index.module.scss
> +    font-family: 'Open Sans';
No need to set `Open Sans`, it's the same as default font-family

2024-08-22 02:52 UTC, chenjiahan commented on website/theme/components/Landingpage/Benchmark/index.tsx
> +        time: 0.49,
Use the latest metrics from the main branch

2024-08-22 02:52 UTC, chenjiahan commented on website/theme/components/Landingpage/Background.compressed.png
Images can be moved to https://github.com/rspack-contrib/rstack-design-resources

2024-08-22 02:54 UTC, chenjiahan commented on website/theme/i18n/zhCN.ts
> +  whyRspack: '为什么使用 Rspack？',
这里用 "什么是" 可能更合适，比较简短
```suggestion
  whyRspack: '什么是 Rspack？',
```

2024-08-26 02:30 UTC, SoonIter commented on website/theme/components/Landingpage/Background.compressed.png
Does svg also need to be moved?

2024-08-26 02:32 UTC, chenjiahan commented on website/theme/components/Landingpage/Background.compressed.png
SVG is small and can be preserved in this repo

2024-08-26 04:16 UTC, chenjiahan commented
> I think rspress theme is a better choice because it is a homepage and it can be used like

Some sites may need to customize the page or theme, so providing components makes it easier to compose.

2024-08-26 07:04 UTC, SoonIter commented on website/theme/components/Landingpage/Background.compressed.png
can be merged first, then extract shared component with 
https://github.com/rspack-contrib/rstack-design-resources/pull/8

2024-08-26 07:16 UTC, chenjiahan commented on website/theme/components/Landingpage/Background.compressed.png
delete?

2024-08-26 07:53 UTC, chenjiahan requested changes
The theme variables seems to be broken:

![image](https://github.com/user-attachments/assets/04fa9531-29ff-4ff6-9588-4ce291a50ab1)

2024-08-26 07:53 UTC, chenjiahan commented on website/theme/components/Landingpage/index.tsx
> +import BackgroundUrl from './Background.compressed.png';
unused variable `BackgroundUrl`

2024-08-26 08:05 UTC, SoonIter commented
> The theme variables seems to be broken:
> 

It is okay on my machine :D

<img width="400" alt="image" src="https://github.com/user-attachments/assets/a0943c8c-60d9-4346-9242-53d0b9165f3b">

2024-08-26 08:11 UTC, SoonIter commented
> The theme variables seems to be broken:


I think it is related to css order and not my fault, lol

<img width="400" alt="image" src="https://github.com/user-attachments/assets/7ec4b164-26e0-423e-91eb-9f8b52b3fd99">

<img width="400" alt="image" src="https://github.com/user-attachments/assets/2ddea06e-dcae-4567-a1eb-5303b12d7a5d">

2024-08-26 08:21 UTC, chenjiahan commented
Get, I can not reproduce this theme issue too..

2024-08-26 08:21 UTC, chenjiahan approved these changes

2024-08-26 08:21 UTC, merged